### ISSUE TITLE
采用自动安装后不显示

### ISSUE THREAD

**Issue by dnpl** [caryyu/jellyfin-plugin-opendouban#10]
DOCKER版jellyfin 10.7.7.设置后在目录中可看到opendouban，安装后也重启了，在插件里不显示，媒体库里也没有opendouban的选项
<img width="713" alt="微信图片_20210927115443" src="https://user-images.githubusercontent.com/22452022/134843253-adc267b5-9f3f-41ca-bf90-4ebac10a6cf7.png">

**Comment by caryyu** [comment]
@dnpl 方便发一下你的 docker-compose.yaml 容器启动配置嘛？我这边测一测，另外 Jellyfin 的启动日志 Plugin Load 的错误日志也发来看看。

**Comment by dnpl** [comment]
> @dnpl 方便发一下你的 docker-compose.yaml 容器启动配置嘛？我这边测一测，另外 Jellyfin 的启动日志 Plugin Load 的错误日志也发来看看。
应该跟这段日志有关，关于docker-compose.yaml 容器启动配置我还不太懂，刚接触docker
<img width="924" alt="微信图片_20210927125154" src="https://user-images.githubusercontent.com/22452022/134847184-76032fe8-f9ee-4589-bf6e-113dd04313ac.png">
这是我配置jellyfin的命令（网上教程的稍微改了一下路径）：
docker run -d

--name jellyfin

-v /mnt/sdc1/qbittorrent/jellyfin/config:/config

-v /mnt/sdc1/qbittorrent/jellyfin/cache:/cache

-v /mnt/sdc1/qbittorrent/media

-p 8096:8096

--device=/dev/dri/renderD128

--restart unless-stopped

jellyfin/jellyfin

**Comment by caryyu** [comment]
@dnpl 从日志来看大概率是由于你使用的 GitHub 镜像地址安装的插件（由于网络原因 zip 压缩包没有下载完全导致），你试试用国内这个镜像地址：https://gitee.com/caryyu/jellyfin-plugin-repo/raw/master/manifest-cn.json 来安装

> 注意：更换之前记得先把之前的卸载和删除。

**Comment by dnpl** [comment]
> @dnpl 从日志来看大概率是由于你使用的 GitHub 镜像地址安装的插件（由于网络原因 zip 压缩包没有下载完全导致），你试试用国内这个镜像地址：https://gitee.com/caryyu/jellyfin-plugin-repo/raw/master/manifest-cn.json 来安装
> 
> > 注意：更换之前记得先把之前的卸载和删除。

很奇怪用国内的根本无法在目录里刷新出来插件，我用的openwrt有科学上网，理论不是我网络问题，如果加上国内的这个链接，就刷新不出来，换成国外的这个就能刷新出来。

**Comment by caryyu** [comment]
@dnpl 那我建议你把科学上网先暂时拿掉之后用国内的试试，或者把 gitee.com 做一下 DNS 过滤

**Comment by caryyu** [comment]
@dnpl 我刚刚试过了国内的镜像是可以的，晚一些的时候我试试境外的这个。

```txt
[09:17:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenDouban, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Douban_1.0.9/Jellyfin.Plugin.OpenDouban.dll
[09:17:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Open Douban 1.0.9
[09:17:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.7.0
[09:17:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.7.0
[09:17:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.7.0
```

我用的下述 docker-compose 配置(由于 wsl2 的网络我还未弄明白，所以把 host 网络设置拿掉了，用的 ports + links 映射):

```yaml
version: "2"
services:
  doubanos:
    image: caryyu/douban-openapi-server:latest
    container_name: doubanos
    ports:
      - 5000:5000
    restart: "unless-stopped"

  jellyfin:
    image: jellyfin/jellyfin:10.7.7
    container_name: jellyfin
    ports:
      - 8096:8096
    links:
      - doubanos:doubanos
    restart: "unless-stopped"
```
