### ISSUE TITLE
能增加一个配置文件用来设置刮削服务器地址和端口吗

### ISSUE THREAD

**Issue by youyifentian** [caryyu/jellyfin-plugin-opendouban#24]
默认地址：localhost:5000，这个能变成手动配置吗，不然想使用其他搭建的服务器的时候完全没得选啊，而且自己搭建必须得用host模式，就是能不能提供个自定义配置得地址就完美了

**Comment by caryyu** [comment]
Hi @youyifentian ，目前该插件设计基础基于服务端与客户端的搭配天然支持自定义 IP 与 Port，服务端的地址由部署的方式来决定对应的 IP 与 Port，而该插件面板设置中也是可以直接修改默认地址的。

**Comment by darkaccount** [comment]
> 默认地址：localhost:5000，这个能变成手动配置吗，不然想使用其他搭建的服务器的时候完全没得选啊，而且自己搭建必须得用host模式，就是能不能提供个自定义配置得地址就完美了

试了试不用host也能用
```
  doubanos:
    image: caryyu/douban-openapi-server:latest
    container_name: doubanos
#    network_mode: "host"
    ports:
      - "映射端口:默认5000端口"
    restart: "unless-stopped"
#    command: -b 0.0.0.0:16000 app:app
```
